# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/Library/Python/2.7/bin:$PATH
#export PATH=/Users/liangchen/Library/Python/2.7/lib/python/site-packages:$PATH

ZSH_THEME="agnoster"

. /Users/liangchen/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh

source $ZSH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
 ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
 COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
plugins=(git textmate ruby autojump osx mvn gradle zsh-syntax-highlighting)

# User configuration

export  PATH=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin:$PATH
export  PATH=~/.composer/vendor/bin:$PATH
export CLICOLOR=1
# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias javac="javac -J-Dfile.encoding=utf8"
alias grep="grep --color=auto"
alias dotfiles="~/dev/github/dotfiles"
alias -s c=vim
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'
alias  -s php='subl'
alias pubmailol='
rm -r ~/dev/yuewen/qd_oversea_webBackend/repositories/server/ol;
cp -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/server/ ~/dev/yuewen/qd_oversea_webBackend/repositories/server/ol/ ;
cd ~/dev/yuewen/qd_oversea_webBackend/repositories/server/ol;
svn add * --force;
svn commit -m "发布ol" ./'
alias pubmailpre='
rm -r ~/dev/yuewen/qd_oversea_webBackend/repositories/server/pre;
cp -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/server/ ~/dev/yuewen/qd_oversea_webBackend/repositories/server/pre/ ;
cd ~/dev/yuewen/qd_oversea_webBackend/repositories/server/pre;
svn add * --force ;
svn commit -m "发布pre" ./'
alias pubmailoa='
rm -r ~/dev/yuewen/qd_oversea_webBackend/repositories/server/oa;
cp -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/server/ ~/dev/yuewen/qd_oversea_webBackend/repositories/server/oa/ ;
cd ~/dev/yuewen/qd_oversea_webBackend/repositories/server/oa;
svn add * --force;
svn commit -m "发布oa" ./'
alias pubensiteol='
rm -r ~/dev/yuewen/qd_oversea_webBackend/repositories/web/ol;
cp -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/web/ ~/dev/yuewen/qd_oversea_webBackend/repositories/web/ol/;
cd ~/dev/yuewen/qd_oversea_webBackend/repositories/web/ol;
svn add * --force;
svn commit -m "发布ol" ./'
alias pubensitepre='
rm -r ~/dev/yuewen/qd_oversea_webBackend/repositories/web/pre;
cp -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/web/ ~/dev/yuewen/qd_oversea_webBackend/repositories/web/pre/;
cd ~/dev/yuewen/qd_oversea_webBackend/repositories/web/pre;
svn add * --force;
svn commit -m "发布pre" ./'
alias pubensiteoa='
rm -r ~/dev/yuewen/qd_oversea_webBackend/repositories/web/oa;
cp -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/web/ ~/dev/yuewen/qd_oversea_webBackend/repositories/web/oa/;
cd ~/dev/yuewen/qd_oversea_webBackend/repositories/web/oa;
svn add * --force;
svn commit -m "发布oa" ./'

alias pubtsf='
rm -r ~/dev/yuewen/qd_oversea_webBackend/tsf-2.0/conf;
cp -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/yuewen_tsf/conf ~/dev/yuewen/qd_oversea_webBackend/tsf-2.0/conf;
cd ~/dev/yuewen/qd_oversea_webBackend/tsf-2.0;
svn add * --force;
svn commit -m "发布tsf" ./'

alias watchMailServ='
when-changed -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/server -c docker exec qidian-website /usr/local/tsf/bin/tsf mailHttpServ restart'
alias watchWebNovel='
when-changed -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/web -c docker exec qidian-website /usr/local/tsf/bin/tsf qdEnHttpServ restart '
alias watchHybrid='
when-changed -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/web/website/app.webnovel.com -c docker exec qidian-website /usr/local/tsf/bin/tsf qdEnHybrid restart '
alias watchInnerapi='
when-changed -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/web/website/innerapi.webnovel.com -c docker exec qidian-website /usr/local/tsf/bin/tsf innerApiWebnovelServ restart '

alias watchAsynTask='
when-changed -r ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/repositories/qd_web_oversea/server/backend/asynTaskServ -c docker exec qidian-website /usr/local/tsf/bin/tsf qdEnAsynTask restart '


alias logsQdWebsite='tail -f ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-website/logs/*/*'
alias dockerMysql='docker exec -it qidian-mysql mysql -uroot -pyuewen'
alias dockerBackup='docker exec CONTAINER /usr/bin/mysqldump -uroot -pyuewen DATABASE > backup.sql'
alias dockerRestore='cat backup.sql | docker exec -i CONTAINER /usr/bin/mysql -uroot -pyuewen DATABASE'
alias dockerRedis='docker exec -it qidian-redis redis-cli -a :'
alias logsNginx='tail -f ~/dev/yuewen/qd_docker/qidian-docker-1.0.0/qidian-nginx/logs/*'
alias joversea='ssh liangchen1@115.159.217.38 -p 60022'
